# MOOC Econometrics

## Test Exercise 2

$\require{cancel}$

This test exercise is of a theoretical nature. In our discussion of the $F$-test, the total set of explanatory factors was split in two parts. The factors in $X_1$ are always included in the model, whereas those in $X_2$ are possibly removed.

In questions **(a)**, **(b)**, and **(c)** you derive relations between the two OLS estimates of the effects of $X_1$ on $y$, one in the large model and the other in the small model. 
In parts **(d)**, **(e)**, and **(f)**, you check the relation of question **(c)** numerically for the wage data of our lectures.

We use the notation of Lecture 2.4.2 and assume that the standard regression assumptions A1-A6 are satisfied for
the unrestricted model.

* The restricted model is obtained by deleting the set of $g$ explanatory factors collected in
the last $g$ columns $X_2$ of $X$. 
* We wrote the model with $X = (X_1 \, X_2)$ and corresponding partitioning of the OLS estimator $b$ in $b_1$ and $b_2$ as $y = X_1 \beta_1 + X_2 \beta_2 + \varepsilon$, estimated as  $X_1 b_1 + X_2 b_2 + e$.
* We denote by $b_R$ the OLS estimator of $β_1$ obtained by regressing $y$ on $X_1$, so that $b_R = (X_1^T X_1)^{−1} X_1^T y$. 
* Further, let $P = (X_1^T X_1)^{−1} X_1^T X_2$.

**(a)** Prove that $\mathbb E \big[ b_R \big] = β_1 + P\, β_2$.

* $\mathbb E \big[ b_R \big] = \mathbb E \big[ (X_1^T X_1)^{-1} X_1^T y \big] = \mathbb E \big[ (X_1^T X_1)^{-1} X_1^T (X_1 \beta_1 + X_2 \beta_2 + \varepsilon) \big] =$ 
* $\ ... \ = \mathbb E \big[ \cancel{(X_1^T X_1)^{-1}} \cancel{X_1^T X_1} \beta_1 + (X_1^T X_1)^{-1} X_1^T X_2 \beta_2 + (X_1^T X_1)^{-1} X_1^T \varepsilon \big] =$ 
* $\ ... \ = \beta_1 + \underbrace{(X_1^T X_1)^{-1} X_1^T X_2}_{P} \beta_2 + (X_1^T X_1)^{-1} X_1^T \cancelto{0}{\mathbb E \big[ \varepsilon \big]} = $
* $\ ... \ = β_1 + P\, β_2$

$\square$

**(b)** Prove that $\text{var} \, b_R = σ^2 (X_1^T X_1)^{−1}$.

Some facts: 

* $b_R = \beta_1 + P \, \beta_2 + (X_1^T X_1)^{-1} X_1^T \varepsilon$ (shown in **(a)**)
* $b_R - \mathbb E \big[ b_R \big] = \beta_1 + P \, \beta_2 + (X_1^T X_1)^{-1} X_1^T \varepsilon - (β_1 + P\, β_2) = (X_1^T X_1)^{-1} X_1^T \varepsilon$
* $\mathbb E \big[ \varepsilon \varepsilon^T \big] = \sigma^2 I$ (shown in lectures)

Let's show that $\text{var} \, b_R = σ^2 (X_1^T X_1)^{−1}$:

* $\text{var} \, b_R = \mathbb E \Big[ ( b_R - \mathbb E [b_R] ) ( b_R - \mathbb E [b_R] )^T \Big] = \mathbb E \big[ (X_1^T X_1)^{-1} X_1^T \varepsilon  \varepsilon^T X_1 (X_1^T X_1)^{-1} \big] =  $
* $\ ... \ = (X_1^T X_1)^{-1} X_1^T \ \underbrace{\mathbb E \big[ \varepsilon  \varepsilon^T \big]}_{\sigma^2 I} \, X_1 (X_1^T X_1)^{-1} = \sigma^2  (X_1^T X_1)^{-1} \cancel{X_1^T X_1} \cancel{(X_1^T X_1)^{-1}} = $
* $\ ... \ = \sigma^2  (X_1^T X_1)^{-1}$

$\square$

**(c)** Prove that $b_R = b_1 + P \, b_2$

* if $X = \big[ X_1 \, X_2 \big]$, then $X^T X = \begin{bmatrix} \unicode{x2013} \, X_1^T \unicode{x2013} \\ \unicode{x2013} \, X_2^T \unicode{x2013} \\ \end{bmatrix}$ $\begin{bmatrix} \mathop{X_1}\limits^{|}_{|} & \mathop{X_2}\limits^{|}_{|} \\ \end{bmatrix}$ $= \begin{bmatrix} X_1^T X_1 & X_1^T X_2 \\ X_2^T X_1 & X_2^T X_2 \\ \end{bmatrix}$
* so $X^T X \, b = X^T y$ can be written as $\begin{bmatrix} X_1^T X_1 & X_1^T X_2 \\ X_2^T X_1 & X_2^T X_2 \\ \end{bmatrix} \begin{bmatrix} b_1 \\ b_2 \\ \end{bmatrix} = \begin{bmatrix} \unicode{x2013} \, X_1^T \unicode{x2013} \\ \unicode{x2013} \, X_2^T \unicode{x2013} \\ \end{bmatrix} y$
* or $\begin{bmatrix} X_1^T X_1 \, b_1 + X_1^T X_2 \, b_2 \\ X_2^T X_1 \, b_1 + X_2^T X_2 \, b_2 \\ \end{bmatrix} = \begin{bmatrix} X_1^T y \\ X_2^T y \\ \end{bmatrix}$
* from the first row we have $X_1^T X_1 \, b_1 + X_1^T X_2 \, b_2 = X_1^T y$ (1)
* also, for $b_R$ we have $X_1^T X_1 \, b_R = X_1^T y$ (2)
* by combining (1) and (2), we get $X_1^T X_1 \, b_R = X_1^T X_1 \, b_1 + X_1^T X_2 \, b_2$ 
* let's multiply it on $(X_1^T X_1)^{-1}$ to the left:
* $ b_R = b_1 + \underbrace{(X_1^T X_1)^{-1} X_1^T X_2}_{P} \, b_2 = b_1 + P \, b_2$ 

$\square$

Now consider the wage data of Lectures **2.1** and **2.5**. 

* Let $y$ be $\log \text{Wage}$ (500 × 1 vector), and 
* let $X_1$ be a (500 × 2) matrix for the constant term and the variable `Female`. 
* Further let $X_2$ be a (500 × 3) matrix with observations of the variables `Age`, `Educ` and `Parttime`. 
* The values of $b_R$ were given in Lecture **2.1**, and those of $b$ in Lecture **2.5**.

**(d)** Argue that the columns of the (2 × 3) matrix $P$ are obtained by regressing each of the variables `Age`, `Educ`,
and `Parttime` on a constant term and the variable `Female`.

* let $x_3, x_4, x_5$ be `Age`, `Educ` and `Parttime` resp
* $P = (X_1^T X_1)^{-1} X_1^T X_2 = (X_1^T X_1)^{-1} X_1^T \begin{bmatrix} \mathop{x_3}\limits^{|}_{|} \ \mathop{x_3}\limits^{|}_{|} \ \mathop{x_5}\limits^{|}_{|} \\ \end{bmatrix}$
* so we see that the columns of $P$ are $(X_1^T X_1)^{-1} X_1^T x_i$ for $i = 3, 4, 5$
* $(X_1^T X_1)^{-1} X_1^T x_i$ is the OLS estimator of $x_i$ from $X_1$, where first column of $X_1$ is a constant term, and the second one is `Female`.

$\square$

**(e)** Determine the values of $P$ from the results in Lecture 2.1.

**Lecture 2.1, slide 7:**

* `Age` = 40.05 - 0.11 `Female` + $e$
* `Educ` = 2.26 - 0.49 `Female` + $e$
* `Age` = 0.20 + 0.25 `Female` + $e$

So $P$ is 

* $P = \begin{bmatrix} 40.05 & 2.26 & 0.20 \\ -0.11 & -0.49 & 0.25 \\ \end{bmatrix}$

To check it, let's use the data:

In [1]:
import pandas as pd
import numpy as np

wages = pd.read_csv('Train21-wages', sep='\t')

In [2]:
wages.head()

Observ.  Wage  LogWage  Female  Age  Educ  Parttime
0        1    66    4.190       0   49     1         1
1        2    34    3.526       1   42     1         1
2        3    70    4.248       1   42     1         1
3        4    47    3.850       0   38     1         0
4        5   107    4.673       1   54     1         1

In [3]:
def with_bias(df):
    X = df.as_matrix()
    return np.hstack([np.ones((X.shape[0], 1)), X])

In [4]:
X = with_bias(wages[['Female', 'Age', 'Educ', 'Parttime']])
X[:10]

array([[  1.,   0.,  49.,   1.,   1.],
       [  1.,   1.,  42.,   1.,   1.],
       [  1.,   1.,  42.,   1.,   1.],
       [  1.,   0.,  38.,   1.,   0.],
       [  1.,   1.,  54.,   1.,   1.],
       [  1.,   1.,  54.,   1.,   0.],
       [  1.,   1.,  47.,   1.,   0.],
       [  1.,   1.,  39.,   1.,   1.],
       [  1.,   1.,  25.,   1.,   0.],
       [  1.,   0.,  59.,   1.,   0.]])

In [5]:
X_1, X_2 = X[:, :2], X[:, 2:]

$P = (X_1^T X_1)^{-1} X_1^T X_2$

In [6]:
P = np.linalg.inv(X_1.T.dot(X_1)).dot(X_1.T).dot(X_2)
P.round(2)

array([[ 40.05,   2.26,   0.2 ],
       [ -0.11,  -0.49,   0.25]])

Our $P$ obtained from the slides is $P = \begin{bmatrix} 40.05 & 2.26 & 0.20 \\ -0.11 & -0.49 & 0.25 \\ \end{bmatrix}$ - it's the same

$||$

**(f)** Check the numerical validity of the result in part **(c)**. Note: This equation will not hold exactly because the
coefficients have been rounded to two or three decimals; preciser results would have been obtained for higher
precision coefficients.

In **(c)** we established that $b_R = b_1 + P \, b_2$. Let us verify that

In [7]:
y = wages.LogWage
b = np.linalg.inv(X.T.dot(X)).dot(X.T).dot(y)
b.round(2)

array([ 3.05, -0.04,  0.03,  0.23, -0.37])

In [8]:
b_1, b_2 = b[:2], b[2:]
b_1.round(2), b_2.round(2)

(array([ 3.05, -0.04]), array([ 0.03,  0.23, -0.37]))

In [9]:
b_R = np.linalg.inv(X_1.T.dot(X_1)).dot(X_1.T).dot(y)
b_R.round(2)

array([ 4.73, -0.25])

In [10]:
b_R_c = b_1 + P.dot(b_2)
b_R_c.round(2)

array([ 4.73, -0.25])

The results match

$||$